src/Vetta.Person/Models/Enum/ClassificationTypeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Vetta.Person.Web.Models
{
    public enum ClassificationTypeViewModel
    {
        [Display(Name = "Ativo")]
        Active = 1,
        [Display(Name = "Inativo")]
        Inactive = 2,
        [Display(Name = "Preferencial")]
        Preferential = 2
    }
}

src/Vetta.Person/Models/Enum/PersonTypeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Vetta.Person.Web.Models
{
    public enum PersonTypeViewModel
    {
        [Display(Name = "Física")]
        Individual = 1,
        [Display(Name = "Jurídica")]
        Corporate = 2
    }
}

src/Vetta.Person/Models/PersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Vetta.Person.Web.Models
{
    public class PersonViewModel
    {
        public PersonViewModel()
        {
            Telephones = new List<TelephoneViewModel>();
        }

        public Guid Id { get; set; }

        [Display(Name = "Nome / Razao social")]
        [StringLength(100, ErrorMessage = "Tamanho máximo de 100 caracteres")]
        [Required(ErrorMessage = "Nome / Razao social é obrigatório")]
        public string Name { get; set; }

        [Display(Name = "CPF / CNPJ")]
        public string Document { get; set; }

        [Display(Name = "CEP")]
        public string ZipCode { get; set; }

        [Display(Name = "E-mail")]
        [Required(ErrorMessage = "e-mail é obrigatório")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail em formato inválido.")]
        public string Email { get; set; }
        [Display(Name = "Classificação")]
        [Required(ErrorMessage = "Informe o tipo de classificação")]
        public ClassificationTypeViewModel Classification { get; set; }

        [Display(Name = "Telefones")]
        public List<TelephoneViewModel> Telephones { get; set; }

        [Display(Name = "Tipo de pessoa")]
        [Required(ErrorMessage = "Informe o tipo de pessoa: Física/Jurídica")]
        public PersonTypeViewModel Type { get; set; }
    }
}

src/Vetta.Person/Models/TelephoneViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Vetta.Person.Web.Models
{
    public class TelephoneViewModel
    {
        public Guid Id { get; set; }
        public Guid PersonId { get; set; }
        
        [Display(Name = "Numero de Telefone")]
        public string PhoneNumber { get; set; }
    }
}

src/Vetta.Person/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Vetta.Person.Domain.Core;
using Vetta.Person.Domain.Service;
using Vetta.Person.Web.Models;

namespace Vetta.Person.Web.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPersonService _personService;
        private readonly IMapper _mapper;
        public PersonController(IPersonService personService, IMapper mapper)
        {
            _personService = personService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string search)
        {
            var viewModel = _mapper.Map<IEnumerable<PersonViewModel>>(
                                            await _personService.GetAllAsync(GetFilter(search),
                                            nameof(Domain.Entity.Person.Telephones))
                                      );
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new PersonViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _personService.AddAsync(_mapper.Map<Domain.Entity.Person>(viewModel));

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PersonViewModel person = _mapper.Map<PersonViewModel>(
                await _personService.GetByIdAsync(id.Value, nameof(Domain.Entity.Person.Telephones))
                );

            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, PersonViewModel person)
        {
            if (id != person.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _personService.UpdateAsync(_mapper.Map<Domain.Entity.Person>(person));

                return RedirectToAction("Index");
            }
            return View(person);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Vetta.Person.Domain.Entity.Person person = await _personService.GetByIdAsync(id.Value);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            await _personService.RemoveAsync(id.Value);
            return RedirectToAction("Index");
        }

        private Expression<Func<Domain.Entity.Person, bool>> GetFilter(string search)
        {
            var filter = PredicateBuilder.True<Domain.Entity.Person>();

            if (!String.IsNullOrEmpty(search))
                filter = filter.And(x => x.Name.Contains(search));

            return filter;
        }

    }
}

src/Vetta.Person/Views/Person/Create.cshtml
@model PersonViewModel

@{
    ViewData["Title"] = "Create";
}
<br />
<h2>Criar Pessoa</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Document" class="control-label"></label>
                <input asp-for="Document" class="form-control" />
                <span asp-validation-for="Document" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Classification" class="control-label"></label>
                <select asp-for="Classification" class="form-control" asp-items="Html.GetEnumSelectList<ClassificationTypeViewModel>()">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="Classification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<PersonTypeViewModel>()">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>

            <table id="telephones">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Telephones.FirstOrDefault().PhoneNumber)</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Telephones.Count; i++)
                    {
                        <tr>
                            <td>
                                <input type="hidden" name="Telephones.Index" value="@i">
                                @Html.TextBoxFor(m => m.Telephones[i].PhoneNumber, new { @class = "form-control phone-input" })
                                @Html.ValidationMessageFor(m => m.Telephones[i].PhoneNumber)
                            </td>
                            <td>
                                <button type="button" class="btn btn-danger delete">Delete</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <div class="form-group">
                <button type="button" id="add" class="btn btn-success">Add Phone</button>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar para Lista</a>
</div>


<partial name="_AddPhoneNumber"  />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

src/Vetta.Person/Views/Person/Delete.cshtml
@model Vetta.Person.Domain.Entity.Person

@{
    ViewData["Title"] = "Delete";
}
<br />
<h2>Deletar</h2>

<h3>Deseja deletar esta pessoa ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Classification)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Classification)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Retorna para a Lista</a>
    </form>
</div>

src/Vetta.Person/Views/Person/Edit.cshtml
@model PersonViewModel

@{
    ViewData["Title"] = "Edit";
}
<br />
<h2>Alterar dados</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <div>
                    <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<PersonTypeViewModel>()">
                        <option selected="selected" value="">Please select</option>
                    </select>
                    <span asp-validation-for="Type" class="text-danger" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Document" class="control-label"></label>
                <input asp-for="Document" class="form-control" />
                <span asp-validation-for="Document" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Classification" class="control-label"></label>
                <select asp-for="Classification" class="form-control" asp-items="Html.GetEnumSelectList<ClassificationTypeViewModel>()">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="Classification" class="text-danger"></span>
            </div>

            <table id="telephones">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Telephones.FirstOrDefault().PhoneNumber)</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Telephones.Count; i++)
                    {
                        <tr>
                            <td>
                                <input type="hidden" name="Telephones.Index" value="@i">
                                @Html.TextBoxFor(m => m.Telephones[i].PhoneNumber, new { @class = "form-control phone-input" })
                                @Html.ValidationMessageFor(m => m.Telephones[i].PhoneNumber)
                            </td>
                            <td>
                                <button type="button" class="btn btn-danger delete">Delete</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <div class="form-group">
                <button type="button" id="add" class="btn">Add Phone</button>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar dados" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar para Lista</a>
</div>

<partial name="_AddPhoneNumber" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Vetta.Person/Views/Person/Index.cshtml
@model IEnumerable<PersonViewModel>
@{
    ViewData["Title"] = "Index";
}
<br />
<p>
    <a asp-action="Create" class="btn btn-success">Criar Novo Registro</a>
</p>

<form asp-action="Index">
    <input class="form-control
        search-input" type="text" placeholder="Pesquisar.." name="search">
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Document)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Classification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telephones)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Document)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Classification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @{ foreach (var tel in item.Telephones)
                    {
                        @Html.DisplayFor(modelItem => tel.PhoneNumber) <br/>
                    }

                }

            </td>
            <td>
                <a asp-action="Edit" class="btn btn-info" asp-route-id="@item.Id">Edit</a>
                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

src/Vetta.Person/Views/Person/_AddPhoneNumber.cshtml
<table id="newrow" style="display:none;">
    <tr>
        <td>
            <input type="hidden" name="Telephones.Index" value="%">
            <input class="form-control phone-input" data-val="true" data-val-required="The Telephones field is required." name="Telephones[#].PhoneNumber" type="text" value="">
            <span class="field-validation-valid" data-valmsg-for="Telephones[#].PhoneNumber" data-valmsg-replace="true"></span>
        </td>
        <td>
            <button type="button" class="btn btn-danger delete">Delete</button>
        </td>
    </tr>
</table>

src/Vetta.Person/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vetta.Person.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Person" asp-action="Index">Vetta.Person.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Vetta.Person.Web -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>